name: Clean workflow runs
on:
  schedule:
    - cron: '0 0 1 * *'
# Run monthly, at 00:00 on the 1st day of month.
  workflow_dispatch:
    inputs:
      days:
        description: 'Days-worth of runs to keep for each workflow'
        required: true
        default: '30'
      minimum_runs:
        description: 'Minimum runs to keep for each workflow'
        required: true
        default: '6'

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workflow runs
        # You may pin to the exact commit or the version.
        # uses: dmvict/clean-workflow-runs@c3aa04e9e161c8bec4458966db57bc8a1de4c6bd
        uses: dmvict/clean-workflow-runs@v1.2.1
        with:
          # A personal access token.
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }} # optional, default is ${{ github.token }}
          # A repository from which delete workflow runs. Default is the current repository.
          #repo: ${{ github.repository }} # optional, default is ${{ github.repository }}
          # A filename of workflow or its id. By default, the action grabs all workflows.
          #workflow_id: # optional
          # A branch from which delete workflow runs. By default, the action grabs all branches.
          #branch: # optional
          # Filter for workflow runs conclusion. Accepts all available conclusions.
          #run_conclusions: # optional
          # Determines period during which the workflow runs will be saved.
          save_period: ${{ github.event.inputs.days || 30 }} # optional, default is 90
          # A minimal number of completed runs which will be saved.
          save_min_runs_number: ${{ github.event.inputs.minimum_runs || 10 }} # optional, default is 10
          # Enables dry run of action. Action will print the list of workflow runs to delete.
          #dry: # optional